command: ["uv", "run", "start-server"]

env:
- name: MLFLOW_EXPERIMENT_ID
  valueFrom: "mlflow-experiment"
- name: DATABRICKS_SQL_WAREHOUSE_ID
  valueFrom: "sql-warehouse"
- name: MLFLOW_TRACING_SQL_WAREHOUSE_ID
  valueFrom: "sql-warehouse"
